services:
  - type: web
    name: cleancopy-ocr
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /healthz
    disk:
      name: data
      mountPath: /app/uploads
      sizeGB: 1

