services:
  - type: web
    name: seamlessdocs
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: REDIS_URL
        value: "rediss://default:YOUR_UPSTASH_TOKEN@secure-wahoo-22016.upstash.io:6379"
    healthCheckPath: /healthz
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

  - type: worker
    name: seamlessdocs-worker
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        value: "rediss://default:YOUR_UPSTASH_TOKEN@secure-wahoo-22016.upstash.io:6379"
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    startCommand: "python worker.py"
