services:
  - type: web
    name: seamlessdocs
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: REDIS_URL
        sync: false
    healthCheckPath: /healthz
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    buildCommand: ""     # ✅ Leave blank — Dockerfile handles it
    startCommand: ""     # ✅ Remove this line or keep empty

  - type: worker
    name: seamlessdocs-worker
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    buildCommand: ""     # ✅ OK
    startCommand: "python worker.py"  # ✅ Required for the worker
