services:
  - type: web
    name: cleancopy-ocr
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
    disk:
      name: data
      mountPath: /app/uploads
      sizeGB: 1
