# render.yaml
services:
  - type: web
    name: seamlessdocs
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: REDIS_URL
        value: "redis://...your-upstash-url..."
    healthCheckPath: /healthz
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    buildCommand: ""
    startCommand: "python app.py"

  - type: worker
    name: seamlessdocs-worker
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        value: "redis://...your-upstash-url..."
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    buildCommand: ""
    startCommand: "python worker.py"
