services:
  - type: web
    name: seamlessdocs
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: REDIS_URL
        sync: false   # filled from Redis
    healthCheckPath: /healthz
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    buildCommand: ""
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT app:app

  - type: worker
    name: seamlessdocs-worker
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    buildCommand: ""
    startCommand: python worker.py

  - type: redis
    name: seamlessdocs
    plan: starter
