services:
  - type: web
    name: seamlessdocs
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: REDIS_URL
        sync: false
    healthCheckPath: /healthz
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    buildCommand: ""   # Render will build using Dockerfile
    startCommand: ""   # ❌ Leave blank so Render uses CMD from Dockerfile

  - type: worker
    name: seamlessdocs-worker
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    buildCommand: ""   # Render will build using Dockerfile
    startCommand: "python worker.py"   # ✅ Worker uses worker.py
