services:
  - type: web
    name: seamlessdocs
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: REDIS_URL
        sync: false
    healthCheckPath: /healthz
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    buildCommand: ""  # Leave blank – uses Dockerfile

  - type: worker
    name: seamlessdocs-worker
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    buildCommand: ""  # Leave blank – uses Dockerfile
    # ❌ REMOVE startCommand for Docker
