services:
  - type: web
    name: seamlessdocs-ocr
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: REDIS_URL
        fromService:
          type: redis
          name: seamlessdocs-redis
          property: connectionString
    healthCheckPath: /healthz
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1

  - type: worker
    name: seamlessdocs-worker
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: seamlessdocs-redis
          property: connectionString
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
    startCommand: python worker.py

databases:
  - name: seamlessdocs-redis
    plan: free
    ipAllowList: []
